using UnityEngine;

public delegate void VoidVoidDelegate();
public delegate void VoidBoolDelegate(bool _bool);
public delegate void VoidIntDelegate(int _int);
public delegate void VoidFloatDelegate(float _float);
public delegate void VoidStringDelegate(string _str);
public delegate void VoidVec3Delegate(Vector3 _vec3);
public delegate void VoidVec2Delegate(Vector2 _vec2);
public delegate void VoidTemplateDelegate<T>(T _list);
public delegate void VoidTransformDelegate(Transform _tr);
public delegate void NodeUpdateDelegate(Vector3 _pos, int _nodeIdx);
public delegate void VoidNuclearDelegate(StructureNuclear _nuclear);


[System.Serializable]
public struct SUnitState
{
    [HideInInspector]
    public Transform myTr;
    [HideInInspector]
    public Transform targetTr;
    [HideInInspector]
    public Vector3 targetPos;
    [HideInInspector]
    public bool isWaitForNewPath;
    [HideInInspector]
    public bool isPause;

    public float moveSpeed;
    public float attRate;
    public float attDmg;

    public EObjectType objectType;
    

    public GameObject TurretMissile;
    public Transform missileSpawnTr;
}

public struct SFriendlyUnitInfo
{
    public EUnitType unitType;
    public float curHpPercent;
}

[System.Serializable]
public enum EObjectType { NONE = -1, UNIT_01, UNIT_02, UNIT_HERO, MAIN_BASE, TURRET, BUNKER, WALL, BARRACK, NUCLEAR, ENEMY_UNIT, ENEMY_STRUCTURE, PROCESSING_CONSTRUCT_STRUCTURE, LENGTH }
public enum EState { NONE = -1, IDLE, MOVE, STOP, HOLD, ATTACK, TURRET_ATTACK, LENGTH }
public enum EUnitType { NONE = -1, MELEE, RANGED, HERO, LENGTH }
public enum ECurrencyType { NONE = -1, ENERGY, CORE, LENGTH }
public enum EUnitUpgradeType { NONE = -1, RANGED_UNIT_DMG, RANGED_UNIT_HP, MELEE_UNIT_DMG, MELEE_UNIT_HP, LENGTH }

public enum EUnitFuncButtonCommand { NONE = -1, CANCLE, MOVE, STOP, HOLD, PATROL, ATTACK, LAUNCH_NUCLEAR, DISPLAY_CANCLE_BUTTON, HIDE_CANCLE_BUTTON, LENGTH }
public enum EMainbaseCommnad { NONE = -1, CANCLE, CONFIRM, BUILD_STRUCTURE, DEMOLISH_COMPLETE, LENGTH }
public enum EBarrackCommand { NONE = -1, CANCLE, SPAWN_UNIT, RALLYPOINT, DEMOLITION, UPGRADE, RALLYPOINT_CONFIRM_TR, RALLYPOINT_CONFIRM_POS, UPGRADE_UNIT, LENGTH }
public enum EUnitCommand { NONE = -1, NODE_UPDATE, LENGTH }
public enum EBunkerCommand { NONE = -1, IN_UNIT, OUT_ONE_UNIT, OUT_ALL_UNIT, EXPAND_WALL, LENGTH }
public enum EEnemyObjectCommand { NONE = -1, WAVE_ENEMY_DEAD, MAP_ENEMY_DEAD, LENGTH }
public enum EFriendlyObjectCommand { NONE = -1, DEAD, DEAD_HERO, DESTROY, DESTROY_HBEAM, COMPLETE_UPGRADE_RANGED_UNIT_DMG, COMPLETE_UPGRADE_RANGED_UNIT_HP, COMPLETE_UPGRADE_MELEE_UNIT_DMG, COMPLETE_UPGRADE_MELEE_UNIT_HP, COMPLETE_SPAWN_UNIT, REMOVE_AT_CROWD, LENGTH }
public enum ENuclearCommand { NONE = -1, SPAWN_NUCLEAR, LAUNCH_NUCLEAR, LENGTH }
public enum EStructureButtonCommand { NONE = -1, DEMOLISH, UPGRADE, CANCLE_CURRENT_FUNCTION, DEMOLISH_COMPLETE, DISPLAY_CANCLE_BUTTON, HIDE_CANCLE_BUTTON, LENGTH }
public enum EUpgradeCommand { NONE = -1, HP, ATTACK_DAMAGE, ATTACK_RANGE, BUFF_RATIO, ENERGY_INCOME, LENGTH }
public enum ECurrencyCommand { NONE = -1, UPDATE_CORE_HUD, UPDATE_ENERGY_HUD, COLLECT_CORE, UPGRADE_ENERGY_SUPPLY, UPGRADE_ENERGY_SUPPLY_COMPLETE, LENGTH }
public enum EPopulationCommand { NONE = -1, UPDATE_CURRENT_POPULATION_HUD, UPDATE_CURRENT_MAX_POPULATION_HUD, INCREASE_CUR_POPULATION, UPGRADE_MAX_POPULATION, UPGRADE_POPULATION_COMPLETE, LENGTH }
public enum EHUDCommand { NONE = -1, ADD_STRUCTURE_NODE_TO_MINIMAP, REMOVE_STRUCTURE_NODE_FROM_MINIMAP, INIT_WAVE_TIME, UPDATE_WAVE_TIME, INIT_DISPLAY_GROUP_INFO, INIT_DISPLAY_SINGLE_INFO, DISPLAY_GROUP_INFO, DISPLAY_SINGLE_INFO, DISPLAY_SINGLE_STRUCTURE_INFO, HIDE_UNIT_INFO, HERO_RESURRECTION_UPDATE, HERO_RESSURECTION_FINISH, HIDE_ALL_INFO, DISPLAY_TOOLTIP, HIDE_TOOLTIP, UPDATE_TOOLTIP_UPGRADE_COST, LENGTH }
public enum EHUDUpgradeCommand { NONE = -1, DISPLAY_UPGRADE_INFO, UPDATE_UPGRADE_TIME, LENGTH }
public enum EHUDSpawnUnitCommand { NONE = -1, DISPLAY_SPAWN_UNIT_INFO, UPDATE_SPAWN_UNIT_LIST, UPDATE_SPAWN_UNIT_TIME, LENGTH }
public enum EHUDConstructCommand { NONE = -1, DISPLAY_CONSTRUCT_INFO, UPDATE_CONSTRUCT_TIME, UPDATE_CONSTRUCT_STRUCTURE, DISPLAY_DEMOLISH_INFO, UPDATE_DEMOLISH_TIME, UPDATE_DEMOLISH_STRUCTURE, LENGTH }
public enum EHUDSpawnNuclearCommand { NONE = -1, DISPLAY_SPAWN_NUCLEAR_INFO, UPDATE_SPAWN_NUCLEAR_TIME, LENGTH }
public enum EUICommand { NONE = -1, UPDATE_INFO_UI, LENGTH }
public enum ECameraCommand { NONE = -1, WARP_WITH_POS, MOVE_WITH_KEY, MOVE_WITH_MOUSE, MOVE_WITH_OBJECT, ZOOM, LENGTH }
public enum ESelectCommand { NONE = -1, TEMP_SELECT, TEMP_UNSELECT, SELECT_START, SELECT_FINISH, REMOVE_FROM_LIST, SET_LIST_TO_CROWD, LOAD_CROWD_WITH_IDX, ADD_TO_LIST, LENGTH }
public enum EUnitActionCommand { NONE = -1, MOVE_WITH_POS, MOVE_ATTACK, FOLLOW_OBJECT, PATROL, LENGTH }
public enum EPauseCommand { NONE = -1, REGIST, REMOVE, TOGGLE_PAUSE, LENGTH }
public enum ERefuncCurrencyCommand { NONE = -1, BUILD_STRUCTURE, UPGRADE_STRUCTURE, UPGRADE_UNIT, SPAWN_UNIT, UPGRADE_ENERGY, UPGRADE_POPULATION, SPAWN_NUCLEAR, LENGTH }
public enum EDebugModeCommand { NONE = -1, MOVE_STATE_INDICATOR, LENGTH }
public enum EMenuCommand { NONE = -1, DISPLAY_MENU, HIDE_MENU, LENGTH }
public enum EChangeHotkeyCommand { NONE = -1, SELECT_UNIT_FUNC_BUTTON, CONFIRM_UNIT_FUNC_BUTTON, SELECT_STRUCTURE_FUNC_BUTTON, CONFIRM_STRUCTURE_FUNC_BUTTON, SELECT_BUILD_FUNC_BUTTON, CONFIRM_BUILD_FUNC_BUTTON, SELECT_BARRACK_FUNC_BUTTON, CONFIRM_BARRACK_FUNC_BUTTON, LENGTH }

public enum EPublisherType { NONE = -1, SELECTABLE_MANAGER, ENERGY_UPDATE, CORE_UPDATE, POPULATION_MANAGER, LENGTH }
public enum EMessageType { NONE = -1, UPGRADE_RANGED_DMG, UPGRADE_RANGED_HP, UPGRADE_MELEE_DMG, UPGRADE_MELEE_HP, START_SPAWN, STOP_SPAWN, LENGTH }

public enum EUnitFuncKey { NONE = -1, MOVE, STOP, HOLD, PATROL, ATTACK, LAUNCH_NUCLEAR, CANCLE, LENGTH }
public enum EBuildFuncKey { NONE = -1, TURRET, BUNKER, BARRACK, NUCLEAR, WALL, LENGTH }
public enum EBarrackFuncKey { NONE = -1, SPAWN_MELEE, SPAWN_RANGED, SET_RALLYPOINT, UPGRADE_RANGED_DMG, UPGRADE_RANGED_HP, UPGRADE_MELEE_DMG, UPGRADE_MELEE_HP, LENGTH }
public enum EStructureFuncKey { NONE = -1, UPGRADE, DEMOLISH, SPAWN_NUCLEAR, OUT_ONE_UNIT, OUT_ALL_UNIT, UPGRADE_ENERGY_SUPPLY, UPGRADE_POPULATION_MAX, CANCLE, LENGTH }
public enum ECrowdFuncKey { NONE = -1, COMMAND_KEY, NUM1, NUM2, NUM3, NUM4, NUM5, NUM6, NUM7, NUM8, NUM9, LENGTH }
public enum EOtherFuncKey { NONE = -1, SELECT_MAINBASE, LENGTH }
public enum EDeveloperMenuKey { NONE = -1, COMMAND_KEY, DISPLAY_STATE_AND_FOG, ON_OFF_FOG, MONEY_INPLATION, FAST_BUILD, LENGTH }

public enum EUpgradeETCType { NONE = -1, CURRENT_MAX_POPULATION, ENERGY_SUPPLY, LENGTH }
public enum EUpgradeType { NONE = -1, ENERGY, POPULATION, STRUCTURE, RANGED_DMG, RANGED_HP, MELEE_DMG, MELEE_HP, LENGTH }

public enum EAudioType_Advisor { NONE = -1, ENERGY, CORE, RESEARCH, UPGRADE, CONST_COMPLETE,CONST_CANCEL, PAUSE, RESUME, NUCLEAR_READY, NUCLEAR_LAUNCH, UNDERATTACK, LENGTH }
public enum EAudioType_Misc { NONE = -1, NUCLEAR_EXPLOSION, LENGTH }

// public enum EAudioHero1 { NONE = -1, SHOT, MOVE, LENGTH }